query ArtistsByName ($name: String!) {
  queryArtists(byName: $name) {
    name
    id
    image
    albums {
      name
      id
      image
      tracks {
        id
        name
        preview_url
        artists {
          name
        }
      }
    }
  }
}
