query {
  articles {
    slug
    title
    tier
    author {
      id
      name
      profile_handle
    }

    contributing_authors {
      id
      name
      profile_handle
    }

    thumbnail_image {
      id
      image_url
      href
    }
  }
}