name: publish to NuGet

on:
  push:
    tags:
      - 'releases/*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # This is necessary so that we have the tags.
        fetch-depth: 0

    - name: Set Build Version
      run: |
        $version = "$env:GITHUB_REF_NAME"
        $File = (
          Select-Xml -XPath "/Project/PropertyGroup[@Label='NuGet']/Version" -Path "Directory.Build.targets"
        )[0].Node
        $File.InnerText = $version
        $File.OwnerDocument.Save((Join-Path $PWD.ProviderPath Directory.Build.targets))
        echo "VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh

    - name: Build solution
      run: |
        dotnet build --configuration Release /p:IsNuget=true

    - name: Test Snowflaqe
      run: |
        cd tests
        dotnet test --configuration Release

    - name: Pack Snowflaqe project
      run: |
        cd src
        dotnet pack --no-build --nologo --configuration Release -o ../nuget

    - name: Publish Snowflaqe project to NuGet
      run: |
        dotnet nuget push nuget/Snowflaqe*.nupkg -k ${{secrets.NUGET_SECRET}}

    - name: Pack Snowflaqe.Tasks project
      run: |
        cd tasks
        dotnet pack --no-build --nologo --configuration Release -o ../nuget

    - name: Publish Snowflaqe.Tasks project to NuGet
      run: |
        dotnet nuget push nuget/Snowflaqe.Tasks*.nupkg -k ${{secrets.NUGET_SECRET}}
